language: python

python:

- "2.7"

install:
- pip install pytest

script:

- python hello.py
- pytest -v -rs hello_test.py

notifications:

email:

recipients:

- ale_romero97@hotmail.com

on_success: never

on_failure: always